apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:V2hz1Ta4X3oSHIeqy/ItyjtW/fqNM8/p5+63iS9qsT7gKpybdc903Q==,iv:e/Apqi6jcCoP4VkSIs8ch6zsd0mhdYtOaHA8cDnL5KE=,tag:ReatoW/Op9H1fxAG7+cQWw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ueasdgtcm4dwg8v6pa2yt9hdu5ul0cc8x6xp5hxaay9rgah4a4qqgxxu6z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdTNxTitNWHZrVWpMaFpY
            TFpSS1dTVGgzOVFSNG13dy9zMUZZRzVZVHpBCmxVeFRvcTNJbTdISkdkQTJQRUdY
            cnE4YnNBakxyek5zVkZ3bmdEVnZJdE0KLS0tIFdHZ1FZSE9HQ1pVODFFY3VPQ040
            ekZNY2dxUVNWREdlODFCOUhnZThOYUEKazFTtD6vGOrkghzkoC21UopBFlhdRwt4
            4kRRBJemo5Dun7Vs6q36PzelDGT2USwOg+XDfv1yPgFE+r7J0gOL7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-27T22:07:32Z"
    mac: ENC[AES256_GCM,data:51D/aK4n0VFF/UAyQA7yhBjMCYw4XXhC7fjyYmAsx8I4b5YJcsdGEt83o7J5Jen6nTBALMR0+3z7s1cP/McJb03Ycr+wjJ+S5tVKA70JQMCB/5UsOH9G6KweXN4BOu16IZVI3zXTBv7YC9txp1wWB/4/EMdrKs8ZKYX+LFfdMpY=,iv:dw1C/icMpRfF/Nlq2liHdMCYIIPByu5e/bEzA3SsxXs=,tag:ntyzadMHrNokFJR5bYN0Sw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
