apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:2Z83mHxFQJ7qQjb1GiiGs2Pfjbz3Ld02oSvUCJ/zIPEqAzY6+ONogw==,iv:N+4nDonkRU/he39u1BFJUoycJlPdK4Tyt8fp/4fmDn8=,tag:KU/EXJ3grYzwHkks9+v4fA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ueasdgtcm4dwg8v6pa2yt9hdu5ul0cc8x6xp5hxaay9rgah4a4qqgxxu6z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNM2ZqZVR1S2RhOG9jZy8v
            U3BEc2FFRnNyUVVIbVQ4Q0RWdzl4bG81WTFBCkg4dkVVVkhvaW9oUlUxN3NyNjdi
            R2VIRHJPYlovWmc1UXZnR2h3MG01QjQKLS0tIGxIQzdIUXlWQXpWdy9ZTlB3TzdN
            OTZ0NHR6UXRSNStNVyszbXJORU4xS0EKrgvRlVX++tVlwgOs2BksOgzN9ofCqnyv
            0suFK3Qi3jqfmUF2+Z38xywfyJ519S7N2cQAjhzNd7scheRC6jwlyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-05T22:49:12Z"
    mac: ENC[AES256_GCM,data:S3OdyvI/OO4LWdHXw3AYwJsmTGm+EZxWpg0p9kjPQ7qY6mWhOtkmhevIYdinO7//eHOKX+mPqjYFrkKZU4YtC8vZlBIYYzc2btqQbkPReCOlrpHr4r3tQ94Ikaz9VF3wyzpXGKT/edF5gOCy+23H0w0Hn+fNsgd9PZvVgn7/RoA=,iv:emv2zrcN2fNG0l2Ya1R0PnqraflhSLg5qs5BDI02UVQ=,tag:SfV5EK+2xM07PWmZ+/z9dA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
