apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:dO/6mWMMMdTIf0wO77qU437dDvvwyGqj2tEmJgKP02DBVghTMik3uA==,iv:tQIYJqzH3JdTltSKFXeW6/8SOCX50IUzlzLqd77aVgc=,tag:7XBFNKExUhsPyM1RmCpoIg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ueasdgtcm4dwg8v6pa2yt9hdu5ul0cc8x6xp5hxaay9rgah4a4qqgxxu6z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRDlSeUpWdzNUaVFuRSs5
            MHdxWS8vM1FGZmlydDBsU3MzendwM2R2bEdJCnZhTkQzWlpYL21weGt1dWhGQlZX
            RTBkTG8xRjliM3lZUUdKb1JUM0s1RE0KLS0tIEJaYTZEV1o1dTJlRG5YYWptY3Y0
            SHV4Z0hrZHpjclVHbXBlTXovZ3BzU0EKUK9/wmtEiJr0D74hM5ILPQzCzvcmztlA
            vbW+rr19f83WoL2ItvzrhOeBv0alXFrCrP9voOIw309gLlTzhZmRcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-07T16:32:44Z"
    mac: ENC[AES256_GCM,data:hsc7SF42RFrelCDOcNw5QTWRPTuZrVR5ymZJR7Okf3rB6V0sBUBG+5Y11bsEP5QX4PPLS2MaDM2Y149g8/FdhcniWMRHyeBy+Rt+y5x9JsvJBC4V21J741axI8mTF2wY4MsJ5EAbc6XTRpqCoMGViUmDfmTNC4Rj/HYTLthLfjg=,iv:aOWV9GKBvT9L6BZj9mXA9nl8/0S+9iY1llC4jgS+aRM=,tag:AzfgLUBGIBI7KD7aJYLISQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
