apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kubernetes-dashboard/ks.yaml
  - cloudflared/ks.yaml
  # - wg-easy/ks.yaml
  # - hass/ks.yaml
  # - nextcloud/ks.yaml
  # - nc-talk/ks.yaml
  # - docuseal/ks.yaml
  # - jellyfin/ks.yaml
  # - vaultwarden/ks.yaml
  # - xepg/ks.yaml
  - xteve/ks.yaml
  # - esphome/ks.yaml
  # - openwakeword/ks.yaml
