---
# yaml-language-server: schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nc-talk
  namespace: nc-talk
spec:
  interval: 15m
  chart:
    spec:
      chart: stun-turn-server
      version: 8.4.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    global:
      stopAll: false

    TZ: America/Chicago
    
    service:
      main:
        enabled: true
        loadBalancerIP: ${TURN_IP}
        type: LoadBalancer
        ports:
          main:
            enabled: true
            port: 5349
            protocol: tcp
            targetPort: 5349
    ingress:
      main:
        enabled: true
        hosts:
          - host: stun.${DOMAIN_1}
        integrations:
          traefik:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: cloudflare         
