---
# yaml-language-server: schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: docuseal
  namespace: docuseal
spec:
  interval: 15m
  chart:
    spec:
      chart: docuseal
      version: 2.7.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    global:
      stopAll: false
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}-docuseal"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"       
    TZ: America/Chicago
    service:
      main:
        ports:
          main:
            port: 10310
            protocol: http
            targetPort: 3000
    ingress:
      main:
        enabled: true
        hosts:
          - host: sign.${DOMAIN_1}
        integrations:
          traefik:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: cloudflare         
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                DATABASE_URL:
                  secretKeyRef:
                    name: cnpg-main-urls
                    key: std
              probes:
                liveness:
                  type: http
                  path: /
                readiness:
                  type: http
                  path: /
                startup:
                  type: http
                  path: /
    persistence:
      data:
        mountPath: /data
        volsync:
        - name: data
          type: restic
          cleanupTempPVC: true
          cleanupCachePVC: true
          credentials: s3
          dest:
            enabled: true
          src:
            enabled: true
            trigger:
              schedule: 0 7 * * *        

    portal:
      open:
        enabled: true

    cnpg:
      main:
        # mode: recovery   # Set to 'recovery' when recovery from S3, also change the revisions 
        backups:
          enabled: true  # Set to 'false' when performing new install (recovery)
          credentials: s3
          scheduledBackups:
            - name: daily-backup
              schedule: "0 0 7 * * *"
              backupOwnerReference: self
              immediate: true
              suspend: false          
          retentionPolicy: "14d"
        recovery:
          method: object_store
          credentials: s3
