apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:eo4JfUe4/oEIvjOjqOIbBMRM3LdOkAagVnY0hzmqigvzFq/dXJAltBw7n2XpsJ5fm/zDiFiLugL61RUODmBQ49P6KriNGNyEx2DDlomF+h2QoJQH9HsydA4BUa04gzTrDZiMXeBZ2VTQjCxU5eU+5YDtO1ibJqfwWm/Zq9ZFFyeYgzYXf6oWLUFhbOY9JL8jSjUNX67mHKEuYdl7mI+TFS8SOTnXGwHI2JEIQ+mQbTeiPR0HWGLbIL0WGyyMFAcJ2hezxXKQslL9twQPyDPoNCtt2GH8mxvZGpQJPf6IjCo0JzfTkfav+upEEuTcRP3WJTzHfhOH1i7Ki3B6tJKbDs4GijTh1tvi+PZS5rcZsXDUBff03gvNTSgRQCUkR57G,iv:xARTwlLtDcCs5T9vMsn4uDjMyG4ry0Fwj4scUreimxM=,tag:zCpEf9NJBVSC9/MLNYBrew==,type:str]
    identity.pub: ENC[AES256_GCM,data:WPWX1Qnk6zKlU7SzYAicMQ+HoYfhwSIfyTBro1vWvtMuA2i/ASOTYlesJCyrPW4yYDkWZqII9TChDHjxNxoxzyUhZ+icUWe1IJ9hVyLe1eN9w9f8rS3YCdw+9UaTi78rxN/i0Uj55v3A/NbSm9od+LTPbtKgdTvjvWlEYgFi99kIwDNCWwJ2voDlMpDNdtauvDmUYm2qnusmP4dwb3BKYQ2yp6CR/4BuJVtKnIaXi7iPnFwYQMSNl3eFI8ZmPfjEB5rHuWh+L3Jxqj2+Kg==,iv:6ygHZWOp/IXiDUfktONZNzjweMXTaxrb5U8GIxM5+WU=,tag:zLasCSgZYO2dHtryMaULqQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:9X40sz2dvoBT+793F3+Vdj4w7L6C5yGHj6c/WGtBGBCdI0Px5DtNyZarjN8EUlz1hOwLVKaj/5ELw84XZOOxqyRiFL21brx0UWEhL51xtxkotGFH79KZAY14F5bzINfNSHvbEibll8otRAdN/4DVdeXGGpvpF+kfb6xWX07u/UsQ19zeCN7GpRTupNjvymWctgDMuYCk3OUXmw8xDfVTaDX/91aZBjK80TsA,iv:Bb+5gy4sPRrUwmm+vb8VuHGm7d9zPIGunejUpt1Rhmw=,tag:G6aKNS/A3xYEjTz5LfMn3Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ueasdgtcm4dwg8v6pa2yt9hdu5ul0cc8x6xp5hxaay9rgah4a4qqgxxu6z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVmJvWHBXOWlDT2V5d3FN
            aXlKYXdhbXl3dExTK0tFZjUrSURFU1NzUUF3CmlwVlBIU05zdEMvdVJWKzBZM3A3
            aGFNNEJVVkpYU2NTL1RMTFFqMVFtZDQKLS0tIFlHQnNpUk8vcy91b1ZDR1FGOHdm
            Ris5U1VkNjVtZzFXR2hReUVkeklFQUEKIBgMe+iCm3qTD8wCpyONnmBEU9AuYuvG
            IRb+VlNIwkw2dB33Vwk76CIgTcyzk9kOF47Ages5ggU/qPpuSLvkbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-30T22:26:49Z"
    mac: ENC[AES256_GCM,data:oIOmWphhrCj0K2lqbJVhijO4dt73B0bLt14f2gJCC1vLOi6jLBch4qE6C+zJIPedDh5LfjKXgyJc6yyoDAb7FjW+BF3S5/marTtq5ZtWllh7nONDQl3lqHopsug7UYegv4wP4bvqc6s165ATj+g/tw6gCtXoAmrLL+xtGXOd38o=,iv:UozWmKgZGWx9OjqOfKDUnUlJemYOddEm1Aiqh1QHJko=,tag:QvzMO8gJQ5QwBifxRWmkjg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
