apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:gskZdTyAuI8+UKyDeTK9otwWn/dpCue2PgN/fzoVCYqAyjgz5XTxxtNVhbdFEhqIVp4dt4rDgq7CgPCBnsdGy7KynGOB5l/eIDNpZ3IoLDAEhzUFZNkETgZfCCXziF2lTT2/HAmnqmrIKwMuSVlfyPUcmYl2NbL3l6iAuMpcQVhdy0xOcOG6jnPZ0MvE4pg4tK9n5BtMvFNNYFgezESP12kPCAJ1aFO61BDlCUBxemYs0hS27CMNch2MdBmVh/EDmoRqJbXKZh0pRLvpZfqbK1jGLqsrBmP3xHv/DBoUETzDZnlffCVX9jwJB3ulYPUHm8vcoDQLU0+5v5WGIco4PMAgRbQ+1IZaKxK74K8CQNme7h2agIgkwRsuJWKW8ICb,iv:zi5W+OSK7UgwIE+xFFdLJyt165cyYABOXw/036lTnW0=,tag:fTLaPjOc8PQ48uhWGJujDw==,type:str]
    identity.pub: ENC[AES256_GCM,data:cnjOM7a8zzuRSMZvsQfCmhhWiTksrHQmM1F4FsXJb0SYrEsILjYvTtTFNVxiWeG/7kN5zsZArQqt2OWvRNbN0myKRS8SPMsuXxIqUnKBWDJuulp9TUc84Na0lqPClqKLlokvH+HBiliRr8Uhk8rk/TfyMz2qG8F3q6B3l6avOxTfd3Wd60AypXf3wPhWhFKnShy5dtVArDdU7uiNqNDZAzQDR/g1ltwgzhU7RKG2HNJfftnJ1DyhXIQBUHUNLV9xBcCPYpFcyka3eaUD8g==,iv:3CDwu5/I3VOQI2H+wnymbgzR9753CRX3S89aR9M3RpU=,tag:vOakJbDKsJgcblGPfc9hfg==,type:str]
    known_hosts: ENC[AES256_GCM,data:JxqJENzzwUMeo6il6amGKNcN9VBcn4XyZ+cyG/9lN9ale9Qw/F+luDZYxEkYwGOfhp8OxFfrx+uaeJ83McMufDmcYVDcrKIaNZ3WVaq+oZYIEoQBF8qW5oi2YMIOXl2zYqT2WL37mjKzoH5DZUYyKei/esqLV9G0egy3yNT2Xsu6k8GWuCrA5trCK3eJ8H5rHYd1WMS63N9i9gERo2bdfvAB+5peTK9Yz7tM,iv:EgbBUTRWquJB9jioCKOqD9EuyCMUx5cZ0SEsc4TN8rs=,tag:7NxF55Z0zGpUPaUGNE+aUQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ueasdgtcm4dwg8v6pa2yt9hdu5ul0cc8x6xp5hxaay9rgah4a4qqgxxu6z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNTdPelN6Wk1zZXUyWUFF
            cDYrMjZCdXV2dzEyZVZyZlhpTkg5NVJWQ25NCnhDZmxRM1puTnhYOTdTbVh1NE9l
            Ymh6ZUxlNnZGNWJLbWFsbFMraHB5YTAKLS0tIFd6cDFzNFh3dXB3MXZRZ3c5TmhV
            VWxoVWovcFBGWjdRcDE2cy9yQ2dpeDgKavp5ouinqDRluYS+ZUN5H3yf4DRiV+hT
            Vt14PJbSb8fY7xXbRwFChof0Ob0wDgkRaJ35DAWLru0wvmJ3iCTGgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-31T23:43:18Z"
    mac: ENC[AES256_GCM,data:k9yu+EHz1Tdln4NMeYuwyNItqrEobc0at05DnncpAmzf+puJWUzT/m8w1b1xStqpET5cpAqYtifMwlvFeww9AD8r2ganqQJEcueE0FaY3rOm7PQzC9oArEULBTbui6INENmlzRthrfqwFC2sGOSr5Zgem4B5lH2nA87UjEu+Fic=,iv:nIR0GThMaWDCGAmhz2AiX72h9WT0rraU7M0lC6RRj7A=,tag:4XnWbLvjgRv843Uw0bfczg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
