apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:zt1RRgq5K5cQGAwdLLHI+8KoATcL+9kB8poD89eneK/OTY+08z00LyfZIysoMRUtz5IwN+6x/MAJKi1z+jvfF9CjZUIydWwYZpzrwRKSr1i/YCZcFu0qLX7dr9aGfJVapBGnol5dWNek6swSDQTCjCTe21126uOFTfQ+PWYU2IP4cR+YOBgqqvH6SAYWOjWTOrfVc1XiE4t9piiX7xvnMdbWpUtRif48Bha1R3lbt7UvvbR6/7LBiazqxTQwc7k7N0Bz+9EospVmh+ejm+75cZZUA6h+PvUdmXtvlsFjyo2Y473wb6MVlt3m+WK5pcn8+721k9VP+IicttDCWC+oaq0COqEjh6S1bJf9i03AR2gXGWXbilWkBBSa9/ABALCC,iv:J9t6LF4uur+99S3IfxrSIoFpfLq/HmsE1oIWvUHJJz4=,tag:PN9v+W7iQrbrX5vsrvU90Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:1fy7qno+m2SV46FRjjDeeXZg6JunUKVn7PgSet5YpTib2zcHl22vZ6UBD9r7tNorG05fXO3wQo2pXVMg8oBXtETwbe+IhQT28l+hGdKRjev6aZD40bKnnYyCFlPEnCJJr7qhlRGGn9kkkbeFXxq9It6/qHIDgzKeNC6+06gQceCFHgWH5HuvoBx4YlKBSq0c8047TE0WGBtq4LEkmT2lqtFPkwB1wmzUXmMg7COcBd1wnwtMmfdXi/6DfeBGGW3Og/w5u5BXgeEa0T42gw==,iv:4t0skDHOnqQhubA3RtH2zb/YCPqb+nFKEJsT+yqbycY=,tag:GUcc3Q0/zYvYWA28UjpF5w==,type:str]
    known_hosts: ENC[AES256_GCM,data:bkHaZ4ODulOkVj3UER836AdgM70BbVNs3en/fiB+NlAKmWzjtTl5swpOG7DfIv4ub5s8s/nhNxAe+erDgrHQgoea2IeHx2pLScI6DdUzSP+/Vkmv1Azi2s/tMoH2GyfespKyRXLz/uRmrU5HqthjxgsCz74n6SUe6hGV/iCd84PrMcNbB9cxQ1k3eJuPW1N3MpwTdN8Iza7yOU05ZstTgpGnvpkH9+ZJLWVt,iv:llC95eKqFE9e7dtLxBaewXtNYuMYFWPQYZZE1MSxH2I=,tag:tlRmmZ+odkSei7jPmMVycg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ueasdgtcm4dwg8v6pa2yt9hdu5ul0cc8x6xp5hxaay9rgah4a4qqgxxu6z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGeVNkNUdjWjdtS0dUNXYy
            R1FGaStlOVNzdUR4QnNuWUNOL2NHcHpTaDNzCitjdGZWMEV0NmhNT0lzUDB2dm5R
            aHBmcEkrTVl2YzFHTTlpQ1dBSlBxSkkKLS0tIDd0OVMvd0hsYXFPVjc0eUhySjlL
            WEhwR3FET0RCTkFKNjJCb1JiVWtOTE0KM/2IPyGTHS94YYnEX8VVnoi3Gl9Y5pat
            hWLjCRO3m7t3IrNHzwJW/yu8EZ94Bqb1Aa+NNm0/K+gQdMOSxv1i4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-28T16:01:01Z"
    mac: ENC[AES256_GCM,data:qyb/oM2BV3dp7g1ALZvUyXdne3dKtGF3IC6USHz0wOH2KwhJ9s6QHedVWOZVAsB4nxVdeTRRwTLhF/dr2BO9zYOtwEK49XmREXBU3PkoFTO600WXG9mmYdZdsqHlNQxXi5IBN9AKtpXwnyVYiwVVuPUjnOg0APWDCj4hNT+UcSE=,iv:+pDpXGmcrcB7v5aP9/AI9L4i9vIICYFMk6Q0Piabop0=,tag:yMqcrKxOJ4EvMs+/hyJapg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
