apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:0yHnC405+CWgAxZLaSxMj/cGyOSOfW75cPSiGFBPGuFgH5qaA/CZ2D019qLvbrfgGU78X4pAjNhaWpomaek3cmwlcB/QloDEoPV9LsGgAsEJmyYvCcRSJpaiA5aV8BR+UFmAgJnyWtXbawr7m0ZaxgsOmW8NIKtlBk9tqgj59TtxxesaMwaQsMOt9gtN+QhBbvL+SpeyyYveOG2j3fwYqnO5SxorlWK9UMpsFoKt3yFg6mYwPsU8GNa89+rEFxBtkXpyg4c8P6y3SBo0o9uekJn6SldwwLZ9sF8p+a+6xqv2MPNf3RLk/bRkh+hbxNRNdvl7PIum2JPvJoP9ZWMRuPsOzgIB1pizCd5Mo6r8bSyO1dZzFeblIESnDjhZK/Tm,iv:veHZHzN4BXTo7nW5/hgVNF9CPds4PD5PCtiYyCa+KOg=,tag:4AGeXj1Z5t7sexAhHUUdyg==,type:str]
    identity.pub: ENC[AES256_GCM,data:VdHVbuuii0gnJTRngjSvzryf/YQEzjed+lBL9ZbMrd6/QrbWctQFI7aNpEaJP1YUYzO4H2JUYyjvW2LM27+D3r6z4dwYUn4eM7LQ2LRZD47nL+tzfC6HsTwL7iKJxa4+k98nWnfs4sbnngz5a9qakJNWS52vae8601XsN+L0hsoK3Suq4Mz/G1KHEF2MjUUk54Y/lNEoE2ae4MV2Hs28DGZMXf/MLVUa/jFjr/9vC+vb5vPNRPg5BeWe3JJCwIb5PDJYymP0hoAo8qYheg==,iv:F/tGDrpzulc2iD1JkZtMSL+QJcq2sDWOHfkzZ5fcV1M=,tag:Cf33qC4oGyABW2ANZ0ARzg==,type:str]
    known_hosts: ENC[AES256_GCM,data:o8gwQz+aawkenVI+f3LHnFjgTKm/m+UGopihi2J1ZLu1jP9aDgsX1CkKZaefmHucVomn3acCJktzB2hHrLywG4bA3aLu+w1vM1t7tJxXFpRmWPg4P9akudyqsuMdVdeDqmR9WPQdgI6KWo9Pi2Da1c/Wmcryv/EalfGk5dqBXvcwA6XYBTa9ptlgxVsKl6RM2EjIeidg0ag47Wm2HVexxr9rUZgd4ozObfnZ,iv:od+paWpHrGag/4vrrLg0yHtyymcXmtheMF/aptE0MG4=,tag:GoPIIlFDXu5xjHIc1xWnfA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ueasdgtcm4dwg8v6pa2yt9hdu5ul0cc8x6xp5hxaay9rgah4a4qqgxxu6z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQURiODJodjRsY09vdkp3
            Mk50Ykw0RlF4cTlhQVo4ZlBmQWh5Qi85VncwClhSWENvYXVHelNlWGhOdjgveFlu
            bWw4Y3FvSFdEOU01bHNuNlB5SC9tcUkKLS0tIHI5bmhPcGRHamkvaW0zQkJzN2w3
            Qi9aQzB6L0pMR3BmL1M4RHg4L1BVSVkK6m9PFLOPWb5K2BcsgLHFq4LcGhuUCmzD
            pvOT7kUpBu8AN+RER2sahKXwq4LohSCuTQzB8PcnkPUcK8Ol2dksRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-30T18:03:06Z"
    mac: ENC[AES256_GCM,data:Z0kwOSPLWDyi3BhThC0hZOLDs9zCHw05zM83N+iisIgLK59rnz8So+nH0rv71QQx9BMWDmZFvC2aO00uIV/duIWotjZKnYJCMKefRdzPxlZXMWJO9KcMpISBWqioRzMC0xE/kC0tBM444gDBl4VjnuEtcRi8+DpMiwsl8YCDKuk=,iv:pJgJvye8OM+onFsEjhjUDcihCUuc6bnAUeDDlusv1eM=,tag:rMfzlbpFoEBFBkaw3TsJAw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
