apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:WUfN53xu7Zoag46VPcL2hSAB3elZowW6KSYP2Amls/h8GHyAoDkhHOm8+Z4bjjvVCqwIeZFxvJq6aUh1FeGaj+CyTEJ8QHh3D6GaE7ZXQ4tRjDM5zR2hvtPQquSI3ZrrLfCpARAXchBIt4iD/iGtVaha4lM59FpTn6nNSd04+Vt+BMxNdeeLkhBHgSh6Kd6Ltn7wYjZ2Qhm0j9Bz1EAuG+uIE47uSWGXr53DFpEIZ9iSkHwM+J6Wu/WHmzz9/EQHm2b11tlSfTfvb4+eCxGV7YxyjB678OyGyW2FADPklGReHH99AfcEM0v5AhLpsLg1vfgMUZ8Ls84NsNlLMSebVXorM9sYbdXM/Ui2hGAHo9SND48hBtEZj7+pTQ79yIt2,iv:9yQB5V5atjJXG/txXcKcWM0uZ195RlSeOWM22PrpIqY=,tag:NA0LuEAz5cvfFRujzZ9BFQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:n4v+NoNdYxPJNYDkaLyXa0gOtZpT4yoQR/zTo60SM3Zgs3vIp7GKykoT/mhkxwdN3/aqgSMQQF277/qmolvPI3XWSkrdPFrh9zvJjPrc3H8tdkMQ0APjjaTcWmHuNytpXsY5pK7Y82wZTVE97IUEelWld0X76V4JPiSPZay8932IlA/kmZhe3Mh61e8lHT3cx3Z1f8ib+73ox2wT8HFpBNWTvxkZf7UT1onsriDU5BI2Fd/jtvcjXfMrK/tXAyzWgdv7xnxkBa7OafgkOw==,iv:EfZ3tR3McIGke8H7lxmPOLtRL1219bRM+wygSxuXk6k=,tag:osnq4o99zyzsr5hVDpZjFg==,type:str]
    known_hosts: ENC[AES256_GCM,data:WG7gNzPmrOq0gFNHp5jsCr+LBG02X+ZO3px7SkAkcb+8dkWYpRM+pWEqv1zDd7E0VCCScovs8MWaqEPb/zclGgtmI+XphQwgLG/cpfIKmGptREagNdfuDagkNzsJecO1yLANEg/vIzgFc8U7mLx4hzYScaYSBPghPjr2bOTi+6MDA3K+JiHhKXTS54PiYI0QL3Euk3JlUooKMO14lcoRIi2tn9RCOcz6IQsv,iv:MJuMPJLwQALN4q+OEqhAxdAiLjafrwOQ9Ss+mU6V/zc=,tag:UjPIwkaZT7s8uxVz/h2FZQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ueasdgtcm4dwg8v6pa2yt9hdu5ul0cc8x6xp5hxaay9rgah4a4qqgxxu6z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwb05tVzdLZ3psTmRpWlAy
            d3pqWERMOFZFZlBiKzhsaHBXb1ZicVJSZ3hZCmdDMGRXQ2Zxc2xOeWlIUUw1QVVO
            VGhNZEh5Qk10aHlWZlFTblpMOW5CeXcKLS0tIGZ3UnZ3UWU0NkhHa3FPcVpRc2gw
            WGRlZC8rMWk3VUdKblY5bTBDRkVKbkEKtSO0+h8G8+L+BipzOv0tHfpSAR67EX35
            9Q7jO7dFbqlVg406SYHbegMEr7hvQXrE74gN6bsQZ3TYB7gYpv9zxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-25T19:25:45Z"
    mac: ENC[AES256_GCM,data:37nOF4s3HZW0VNfgYmHedINWhJjDRXY84OER7FfpIdxY9QOFa5nI156XCo+GY7iQWXJN+1oV5T1mkW4a6Kp6u1Da9xTSq3Kgkq7h45S6cCdzUeR8pDuC3TnPzpOu3bdyph+bRuzIIqyHjjyN2aBfmr/xwklvEWtSNp0PoEvU8Oc=,iv:tLC6VemL/fERJNKRODYlGrExmxBKI18NaUPMukdB4W0=,tag:XfQYhbudAJpXB/T4Xqo69w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
