apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ZlKUfqGzabNmVbNOH25+5d4LZyoShikIiHqoYGv4V+ILgo87UvjWXIg0wdz+W6YtfVKtnYgKlhGXvjv4V+W7qy5UG0yYd/eRgjjTtPqXIPFBHjOg1QZaINq0Yfp/+fit1Y82KGRa2wSaptN6SeYbvF0Bc9zAPpj5SNSR9XoGaltIC+GwlLtf3/cqPOpLB8300sszXyPnDV74u9d7XIOHOvaFEdtxwjc3uawU+cQRnKuF6KwhdtiCqqkZSqaDUiLf/pdbIkTGB8UVLjX/ubbhs8U/GpIbTcHMRse0OR9G+lhe4spxM3tFib/9ilyLANowy6ujYARdg0Ml5gUuekwqLgVOHb7BlqV5ZRlBNZT0nOQDI/m+UP1kRY7K/o2QeJ2E,iv:UhKF0A1CPaGMuKERmXAMALMXv2ppV0bDcEwkV7yKq6Q=,tag:Hb4lUyvy1ehGXxY5bmvDwA==,type:str]
    identity.pub: ENC[AES256_GCM,data:zjYxQRG6i3SCuqw1eJMYn7cCLStrb875mHbnm2Ux+vpRUrnXosmjxB8DHEf7p0fH/SjAyJY+RF1JKvLVS+hkx/em7buN86S26XnDsIdS5qaiVopXzp2cnqvbbGYCoPL6d0OjUf+UgwrKgoDjeNj7CYx8uUq12mVA0aFPcZBIiafqjPHA79TB9oplgUG8jaR3e//HksNPD2NYWRfbuHoRVwcZGJAJYuc80ph1CUtUhgiODL6mWbaYYrMy9bv3e4/L1PCoW6pzt73xlvMvww==,iv:IfBCc6HG+M/j7U709ta2yZid8/uWAobaL9g2M7kbrVA=,tag:J0N8xVhIMa5PCH3EnvQn0g==,type:str]
    known_hosts: ENC[AES256_GCM,data:2+3TPb9jn8zbiq4jvLswIJ2h1+m01ikQWxn51WIBbN7Vf/Gp3xyqJPQINFmyky9atGnHuOQkAEolkoMb+koLbxge/E8xgv9hgEyV0pIawcStosaRz8YXYmCHx71pw2HIYhhIL/JB9kNxXJDVi8a3N72/lKO+AbkwSQn8zuc0MfZs+ksvl28c7JOUPE6OvuIr5Ti4N5ejHmHeyWGc+5PvuURJ8G72tJbCcImn,iv:3m2YqUTN8UwvB7Aa6nPLrn9pCFH7YzYE33cHOlyyhnw=,tag:hOhP9mXq2oOPV8GnZkO4mQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ueasdgtcm4dwg8v6pa2yt9hdu5ul0cc8x6xp5hxaay9rgah4a4qqgxxu6z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1U1pXN2hQeUdvQisvQnBK
            V1hMbk41TjRtdWlJWjRYTGxZT2ExTkkyeW5NClNlaytWV1JMMDUrUWQ1c2ZrVUhl
            UFR6VFZXS2pXK1VTZVliR1Zob2NsaHMKLS0tIGgyNklJZ1hsclFhWjVXeDBKWHdX
            Q296RUI0UW5GekxqUVhLeldlQjdSMEUKNmEZ0mXF2ngrWxiDPnG665STIuBs4LiO
            1Ajv3Vk55A1DrV4eMp6cQeL/b1C+Vi2oDAvmw28zWeLvUloJrozDvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-15T18:19:23Z"
    mac: ENC[AES256_GCM,data:gAdve6K5L25YX6zzBM+X3R5Uj1KSaNSt1xxIVWemLL8L9bP9kFQjysYaT2C3feyzAJ7+W2I5olMxGdIH2jXO7cIDTO+xi/hFJikiSo/65yXjAIwh10/2hKJ4B3RDJ6CUEk9UaEPP60frZybtoIBtis99xiAAqS8q0dGS6soG3kY=,iv:pA5qLnF0awN8zVT+/hCXEGOY6v/i5wTga4mot2+YuU4=,tag:uRfMUxtrF0XR8hAt4zzktQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
