apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:WSXOF07KIDpi+u1UWvIri0b1FkKGkDrXD9ZFkGVrscTblgRfAtQrSKkkeL/kqZFmZcowzkgcn8qp9keNwJnOzWXYy0srw/K5Xe7Wyy3Q1j++nOauzvlj0mw9vz1PJrErtx5ikW9hhCmujPRFTWaL/dI6tpt0o+rKcdmH0F2m76LMlmnYICuK/GkznAq+foQLEqz29R9ITiKjOW7wtGU9he/QY1zKOy11dv0ArGGlImfhUHMBa+nw9QrnKccU6hW6WiOq+8zkptF1rnmlA7s433t8egO8+/eEWw6GLmd2Ku0X0l4FhrvEEAAeaKx6AhySPOvxKNWW6JiacdjDo1E8oWBYt2cWW1YcbRe/tctkht/wwcQPvnJuVLLwD8XBlZzV,iv:HVHvKJnX1RD4yJ5d/Tqz9qIuZh5ikINy/hwnMn5N5n4=,tag:o+nPUgl4+k5sH5VHgE5LIg==,type:str]
    identity.pub: ENC[AES256_GCM,data:lqRENpU2TGnDO9b6gpzgNxbfSpva3gYbD4K3JW4tET3F6GZoeEAhImlL3eQocbHkm0dlxdMBWXZy88Fk+1Vgk3JHEaBMiOQeSIc8gFOGqNduStinqAW6oH8kMZkuovthkFAE+Mk7DopEsqpk5IC+N32sOOh7eDDwf+uI8YZEiiuQ+L0/G2pZzKB3h+f+wY0MK/jMx27AH1EOXNgcHR7I6nMSaEWvtV+Vk/2tFTjP0+CcAsqO/7sYzoFZeZnU3owc1dU+GAdIP6pEQ2zuCA==,iv:BM8OEmBmkEMvFPqafS1EdlZoYxqUyD2kE7NoFJpi0Kk=,tag:N8TWvvYfVeWZNj5N+1SycA==,type:str]
    known_hosts: ENC[AES256_GCM,data:bLuzRhmXS+/1iCBm9/EJnaim/GKMQqYyPkodQkRH8jVpQpdBxN6mRGrN63FCHeu8b/o4+XuUsDsf/S5ggoAl4BzqJrzM8F5VhxaCr8q1Pd4iZt1WKNBxQDmy1bPtO1OEB20PO6Dl1NcNBN8fFFi3+RrY8d/huXZLbsa7EKOumySpvdX7aV7iWkEDwCkYH6eypxTnHxbeQvVXoeb987q3aXZXioPvv/74Oue9,iv:+ZOHO3cEMx5NX/uVqePIJoFO8QOcmnn54j1J3sZsiAQ=,tag:j74m/XSJa4I7F3cn97hAeQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ueasdgtcm4dwg8v6pa2yt9hdu5ul0cc8x6xp5hxaay9rgah4a4qqgxxu6z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtckFCMEZiZGo3MTEybHhw
            Q3N0MFBCMkw3YVIzUEs1c1dwandQMVFZa0JrCk0rcVZoRFVCRnIrVEdaRDZsVjND
            Si83MGtFMjBjN2lrVFd0SUV5ZUlyUXMKLS0tIDJCeGxGWDd2TGpiTHY4bWFFbitl
            bVQ1Z25SWHNtdlZTSDVpRVlQUFcwaWMKMwsx15B9RR3hA6TPlazras58frba1BmP
            YT82K3ltPXwa+cRKGclLRN4tRKXCvbP5lJJsTGrgxluMw73Fp1JUBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-06T15:45:46Z"
    mac: ENC[AES256_GCM,data:uO+XnLjbCkxa1tDVb6FiJiN/mrCIdFWtHiW2PCwSzxLAim3GjVk8L5mIzoqfLXkP8SsvoYXJ7v+1Y/yX8YvBGXyuZGz9AedAzGDb+LXagod3yQLlLOjE3R3jZvaYzjGvFicRct/kthmgBwuVOHkNE3GeAw4l7VhHEEwv49PF+5M=,iv:06DgByxQgCG3NcZpZa0XvL5jWoKdqcErF+VYlBY34VQ=,tag:2Xi4u1Jb2jei0uD2/H0aZA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
