apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:nM5wLePM3xyogpUWk0Q6hsFmgkWn0yYCVYb3HCo09cO9noaaMOGQTpdJ5KBDfbcGkoMWqCGoHpcmMbGfNQsRibIwkcN8pHLdAceOeE3p0b6lK15YInyJtrTRHN+24N8amu21NJUhQGLYgj38ITUQqFC7mVmlEsRkqzkpTO4WiMxbTzsFwKaGoW+UsZPty97h+Ciw9dB2KPvTUwMGLwpNqhK3v3GSvT3EllqZJ1e1VUc0qckH44Njh0NccVFOuhqqiYv9jFNMG3bc+Xe6n/EBL88t/wf9rkMH9trnZ5Pq/k5MMJeLbvqR9eb/2dTUPuEYmym0h/TZ5evKDcPpIDSt/JkIkkN8MCDszxQyoGmAOM2uLVn2U7YqkX1QEbGUcAUw,iv:LYzlDrd3JsMoAUVvUvUcAcvYpWvzcwRE0CgHu41W9Hk=,tag:jsLR1E/2U3JmmFEyWDydGw==,type:str]
    identity.pub: ENC[AES256_GCM,data:OXziylyUAkfyA8jF8YiuQKL4P3EqhLfw5rUqSpyFDPeeKVp9mppx7BOH9/pIQIQk7JFd4U0MnPvXzhjssAC4vZVkJazbXafVfCxa0Lkvg67PSwE9lmpaj83zhonLPRri99VL9ghFCKAsOhL3RD1fZO+zeBQsgaXcDOk0AXu/WKbJWKrVEz3LqKeTPtN3mcSmDh3R/Km60hwawea66u7E2duUEjDC7eEH9Gwpdfhp03XQy9ta90+bX9pPs+fvJgwGsyBCY/A6K5nYqV4LYA==,iv:54h7QMihKMBDjcKsZrW6DqMD7n+uM1X9YbwE4eT1iE4=,tag:UzbW7mgp+Gc1DHqpkwm+Wg==,type:str]
    known_hosts: ENC[AES256_GCM,data:whNLGtbO5wBJV1ABCyYCbBfN+0+2yxNnCHiMZoP+cOfwT3Q+EOlonOlM0EZvjVfv5UrYlEY+3zvcgBEDEXFnMCBS17JFV7WDhpxHhLKmYdbvoheNWI3PTOSTC6zJKnj5KURN7svuzs2tZNLLsxje6HDUzD0dVXsMo4I6LltVgDMUCDZR3+pE551nw2rh7PpugIBm2YeN3pD/ndztkPQU+hKWCBB/Vch34X7n,iv:Wqx3vWOgU14nf3ecfonu5PKAfVCZOF5t2IPG8kiZ0nA=,tag:wiFRVSnSOkDOfqLu2LC3/A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ueasdgtcm4dwg8v6pa2yt9hdu5ul0cc8x6xp5hxaay9rgah4a4qqgxxu6z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1czNOYlc1STJvMXBjUXJY
            LzUvZXhNQ1N2OFFsTi8xekVFSVVoaTZPMnhNCllsOWUvNldhdzlDM09jemxKT3M3
            RlQ1cDR4dWI5R0VnVHh0amhHeTI4MDQKLS0tIDQyVHN4SDNuVXVFYXBtOHlZWC9q
            blh4V0NTMVhrM25jc1QyN1JjZEZ4T0UK6BJQX1Upp+Yk3wJ8Yw8dXXvf8xyI2QGQ
            5f00SxXiSzOS1u/XWbPDuUANiQmxzrUa6pq0WcX2xuvm2sc0SB0zUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-01T17:54:49Z"
    mac: ENC[AES256_GCM,data:ZAcZb+t8fP6kTqXn2E+BqGcTo/1YP/ZUUjuaNYYIRQCYW/SMlX8e6jTX3MwUyzRMqZl0Eea9AHrD4BSSMAzEK/Jz3bJ82CLvqpMMmGjjtX6tmgEyt5hTiy0XRLf2jMy3wRV412/ikEQbWpBmiE2EAagV0tsdsH2mZyzv4Ge+hT0=,iv:oLZJl7avWMHjM7Etmc5XuSCKJNZT3gYlZrx/m9ndXsM=,tag:cyXgTGi8ibf8YLGmuxF17w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
