apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:L0P2vqryeV+wSUkrUYUSABB1U9L+Wh9IqEQfAKTw5ekQxN4acETC2lQlAWo9jPFlAKlkx+ep4PPexEQPoGzmqRmIg2mU6Nbb22xvKf3xlxvT/PN2ie+MSWps53L7sbsQd7+ENc76yLNX6MIOIB8Pe65JtAfZf6ipWuzRYJjeJ1380gUpWyOULhOVIf3SzxUoStpO/1iXdu2PFpddvIwGF89H1Fd4MR5J+7UJhDTznGc6zhfTk6ZpuxOVw4u7xHCicwAStXwcdA/0IbZGKBRea8y/jBUy+e4rmfVGxJkzZ1OEl7lv3g4Y82L3xzte87u5XfOg3cdZMBhWZ+llCHJNU3Ajcre1FQYKFNKWepoBINEQP4ZGeuHNHKA4d+qxdPCb,iv:SSD1V87Co6njXsCVZ6/hBpl9SOsmPZF3OzbOPgmjyuI=,tag:yh52b6xaDgg562+YHtnCww==,type:str]
    identity.pub: ENC[AES256_GCM,data:oXrvWCGHE9QNP/dwXm08qxE07CYOd8xwCPhtZ0ievw1uYc0eZjnAXMf52BI9GySrAVjR5KrKpYTVDlXGaxGYZpFD7L+Dpdm/UV71/ARfGrTZJx3Cv5NxVGkegAOZ9iDles6f/GlCIYMkye7vGzBs5KUvoEwEXGJqqJOf0X1cxSUMn2Onv2A78avHuVtkJvTx7lOATpVgyvUKjtH6sID1xMHFwOXC7WWpiHYnJXn7hy1OXDGFEr3Tc2LEzj6uMW0Nkh+c5jmzse6acYb7jw==,iv:c1BtwR5RUML5iC9BFMcYlNFbo0LimXmXuv5QkxprmQs=,tag:e/3fXy3PrBG7F+TAqFHGyw==,type:str]
    known_hosts: ENC[AES256_GCM,data:X08u/5bYE+yPnF/UuDcZwJhVygU8qnK8f6jyYJJ5N+Q231Co2vc+MJK10I92eo71/TXY0QkRbJau3ADgmwqKOgcHlu9SSj17T5U/NEG3TXr4uAYWSyJus6r3isX6OdgYNHWgJsVkQ/f8xr8gNy6xQW8pJRxcKyjLJ+Ypuc4CqMVORARVKAVrMr52No9D6T8cT1UQm+JIYo3U6lU2MFlfvFx29zbajKdv0ycE,iv:8Bb2fpqCJRk4G1zteuH3ZdbJ53wStaf5yg3l8s85ncA=,tag:W+Y6KUX1A+KOXdjez3+Pig==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ueasdgtcm4dwg8v6pa2yt9hdu5ul0cc8x6xp5hxaay9rgah4a4qqgxxu6z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTDNxK0IvVzNkaVN0K0s1
            Wk4xMkNpL2Nlb2NJdnVIRHUxOXd5ZHdaTHdNCmhXZmdTUXB6M2hNdXZML28vclh0
            MzAvWitlYWlHblFHV1pTMitqaVVHc3cKLS0tIDRGZXhlUFNPRjJLM1AyNlBsRnhx
            ZGt4VFFJT2FSa1VEWVAycHo5YTdJOHMKPQmB6XvOcvIMJdRK330r8lFKpvstXlNM
            TnBfQgM7/68PKHPJUJWw060UycBz9I192yjVCkw6UzPp8KNFjtGrhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-10T16:14:57Z"
    mac: ENC[AES256_GCM,data:s2jFcxoWL6jp0IhbVwZsSInF46OKYaHvTi6nEUgPzv4uYNhwVYtiKTM12tHUPFzSklvkbvV3rAaUufC0TuvaJCE7p/RA3QCowQHyZzzkwtFqfBYRwshrSgphBx7/mI2kjodssxc7sPx2P6vj2eDU1UATmAZMFDr8AOHvOSYh83o=,iv:uYA9BREL4e99+uLDBQ+15aAOV9a7sq7Za5ZaWYbesSU=,tag:M3sEypSLitSrcgtD70zY7A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
