apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:biB3B9i2cMZATIlmF9ikzwFkzUv2L6Px1z7EoUS2mj3hvk/hGumchVA45Flf5RGxr6jcQpBHePto9MYsA3lAOEvXKSZXk3wX0H9R/9foGXf4Tkp20u8foMCqg9VvTo5ucJ1kcaL//bVH5qVCY2ZKBypd7ZKuRNi2TW6edhn/iPaqehZHBpBAYoyYFyxREIq9GbCbzMizLc/y1A7pDWkGixqzcZ0XHjhhSPGXXMb4a9X+Ovu9nm4UvxUgiVYGGNRSHvzETwDfXNZdpepCPuNdQUd4AUkZWFQwndDUv99MbTaVGillX2V2s03p/QE4PN+lM00ccsjupqxavZXnSm4JzapreXHrt17gsfFqcmfSuly8GIlBnwz8AtfCm0yB/RxP,iv:6NwkcKmPiW7lt4P80e0DgjcH0TVIvbzNrHJTYezE7jg=,tag:rvH73MnFpSQghGqGLmKZ5w==,type:str]
    identity.pub: ENC[AES256_GCM,data:AReAHaaDvgLNqiHrVq/vELZ8nfMuLtKUY6AWmx7BjTC3GfIjrg8sJi7ZP6IHGqzMSdL5qs7H8rPdrNO5cbRHgMIECnmAx86QToVGp8xi0rYJx7n7t4hXLw8318FSrTiAZEO5IiWziFzhCktSyfWYS4Lpqv5hEF9iiedoHjInKDY+hFCjdA6daqnWuFGhMafkO+FQfA0oujw8TYq7s3G4MDH0c94cGIdQkRGE/ojCU5U91uMORwUQRKCyET7txDZ4fP7pi43P1W3YthV0jA==,iv:oMERDxW1hVNBrxwjB/Sncqb4kUhPdlAAYfAjRq1boJ0=,tag:kTugKmxUqZ7nv7ARJJd0rw==,type:str]
    known_hosts: ENC[AES256_GCM,data:Fir+bpgs9aOfpRZrRmLwX3+Ij0xUclQ43DDvexgpGuPaNgWmVfBCxo58f+Z6GYatka4B28S3c6+yniy+USslsJzg+5Jk0JAWt//az+FvUcbL45Q01I/w395IQNdrKmVB4uMvWhBgQunpwiTsmx+mKNTxfhr0Pzm5P/rSb2sx21G+Cya4/F79HpZGYFtrKsGA9EklwarBdm3rRqyctL/bC+6M+JlQm7YWm9wq,iv:/SZiUyL6kjNZ+I190AABPDCCtT6iQboSk+hDSIoWPiY=,tag:XVc4D+L7gO0bJVQqJJJ/hg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ueasdgtcm4dwg8v6pa2yt9hdu5ul0cc8x6xp5hxaay9rgah4a4qqgxxu6z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0c09FUmVEcWttUzVHeUxE
            c0kvaHUxaStmdkJxN3VFMTlTN3o1aytuSFUwCmFMQWNyakh2RG5mOEJMbTQ2VEw1
            UHlXdExqWUc0cE55OTBLWkdrSDdHRjgKLS0tIDA2WnhGdk01TWlqNlBBZkQveHkr
            a2QyeTNWVTBOSU1SUmZEaFNmSFBsTEEKA7YVKgSRo/QfitlHybOXOTjElg82CwVA
            wH3cscQ+KhWho07T9DzAG60/PT9IjIbm/xZv8HIg6/hoSqDY2Ueglg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-08T23:24:49Z"
    mac: ENC[AES256_GCM,data:++w9PNJclYgXvvX17os82XUMvEChRaqFlIkCyBDbFDLG99n+q+G2o/jabeP2Ks/QndWXtuo/w2BEDL72wdtsQjgdBJkI+Zze+0iUBe57Vd/sAqbScu2pAJVU3XNiosJZvezJi2hw4aNTh9AqAZUcXJlFsrSUkO+2RfzMZ6i8i1o=,iv:DV+GPz7EkijfUMHJfIIgTXt9m5RmvCsCyik3/FVsZP0=,tag:wNITKWjvqenTO8Q4axLc2A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
