apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:KPX3ci3isj8xpt14oVDn5k+YgRG9eBTY36kQgWpMzxn+j6k78dh5Zyk96IYiuMe19SgE0N2g0WdeyeB7P+DpIEp7r7lsLtwQpFi/RfdyA3Yue7cNVigzeg2KwA/tt3m1zaRsobnxam6iDP74hK3EV574w44ao6dMru7+60h6kk9y4VDI/RlD7P778RKG68STy2Pp3xoLeymO8RIy2/eSxDIUJWt4liysV5ey5SB/woXITOyIs2NMog4dyR2L5tlhBNbhB4GhT4QfEuVqSRI0RyvGQzsufJM66ep683/ymGWAIVFBQNFh5gKsD+8IWvQoKMQQyPS+BaMbqm6Ri+2iyXQX92ix0d43vhX3pfwPUX89OzRXIPBXFE8AI4b1VTPI,iv:2zzJsUBe1B79QjQBpsuVueqN7inocq4wlKVd4xxnt5Q=,tag:3/TVeY/xYs0w1ma0Uc0P3A==,type:str]
    identity.pub: ENC[AES256_GCM,data:oZhRFPBaypHjiDHxCPKs7d016GncoFicATI8JRGneh6/5VcgWw/7ZDN0ZHrYVPm6FqRTebfR5VuwBng0ugvKtouiFasZYVvTYeghxON0Ys4+29RmncTsm5/lG6TPwEYQqlos3Km3EavZ9dIaWCVcVNF632gUbkW3hWtcW2MZoGIlzwZrt/wCZ9IEua03g7WNnQZk9scyXZww+IsquWQjkQWbVX0JGrGTTFwyLTESOUTrE8/R27Lz6CX6z5+KzHygpn2WKOD+ynXIm3BmwA==,iv:AH1yt0oQBaM29KG/Su8RxfrHAHDfw7RA4cK9yjKRaag=,tag:3lJitAQB/Li2jWoM+G8EmA==,type:str]
    known_hosts: ENC[AES256_GCM,data:SIWYXNIPewocZRkNgKWYwuJHY56rEop+Z0a27neYTn7GOAWjR+p0FNVU5EsAaaayy4JXzVEFm0GXP+MtpRW9Fk2zA/Gye2LqavjqrY9ZO5LPHlK2JYS+gLgB0jw82NXv2vVBrQa+dN+84It0NS6kdUk8VVBHsMjLWhZ0BR45B9UikTCJpD1E1G8V38O3oL8KVXKB9VOitzp3fBtkXEqPIAJdChzUH1cE/6Rp,iv:pf87mtHzAlYEvMSkGb0akMVHSldmSRSpb1+e6NHp4rk=,tag:80Q7UJiyBdK0k/oQ1Qxisw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ueasdgtcm4dwg8v6pa2yt9hdu5ul0cc8x6xp5hxaay9rgah4a4qqgxxu6z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXK2VmYUNGR3ozaVAvUEVC
            bHM4bmdJcDdhaml5eVRnYUxZTGtKaWJkT3d3Cis5dlYyRDNwcGNOT3dseGhjdDlY
            TUxWalEyZnRPTXVDWGFMbFB5UVkyUncKLS0tIGhQYTBwVVp0R0ZmUklLd2ZlOGhw
            V1lhUTRQTCtraVBxOHNseEgyN2V4aWcKhsAAQkJOl7GKAnv1AotdGIRituENWvpr
            jTFRddnzswTa8pymFDyL4o4AE7wTF4oeQg5dDK7x5AyId6NwBlG+IQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-05T23:29:52Z"
    mac: ENC[AES256_GCM,data:33EISpGhYc6biXQnJv2u3eTYux1PmaydTkxFPl01wkU0UXOhqtMOq/qXcqrifOYEKSL2ZSzMvl235mNCJkXfnHzTMmdOdfP4QBOQHUtTcb0hleZuaaVNCsCgIdVa+A+H74Dbg4QzJjAoCFmOo75D/nfJWGnbviDWerQdgnfjLUM=,iv:K6EwU8f+So0hj2mIBL1Cun8wwD7upU2GjLI9Ii7Wwn0=,tag:5cJU6VAWKY6Fso8XNCcm7g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
