apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:maLMvziENF+vsHkR+kkERf87MV516HOiR26op4nrmAa8UNWGK1UAR3HEyWykIcITwwMtC0M5StXaO5WeAMFIJCt2j5omqorS/O79G+jo+A7Wr/+HWi8mTQFeLwaTZRZyeu5rgiDqNcDOfYw3nr/QO43zSuQ7uyooE8pSmScIsQAK4AHcNTlxwTFk0N2bA4lK4eLvKpLKUGEhFGuQPsxVWjX9/j8g8xyyiP/u/MBXcBT99aIQslCPtFNOp7gOkCwQ7WfHMADIm2Fayw463dK019mbnr+yFNTiUHFchR5zSnI/Gsqy8uT0UsfMrMnq5Gwzsq/kZaBo/0J+PX3GRZ+ChyqWiMDWgqBCT00YOCYvcGa42eBXCJCY75E639mT497E,iv:Ucg+tTf3Au6HwIaUEN4TsU8Ts0UZ5f+/xaHe0Bjn4A0=,tag:Y58jBcru+1Rd5k6IgP8lOQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:h5SLSlOx88uPyfXrfYRICQ5BonwXOcZkV7aeOJ4ZFlIHJynSVp5zxBtcKQ7Bia7nVST2kjpxObEVKpu2GnemcfY8iMgCGqbaISdC4eMNlPzunZ6EEAwIfNRxFSQCERh9jW8hXlHzfrtuPbG4X8vMuvWF1nBO7NLWFk+TQU1pwZY2NKztLFClzqVqidPo9+77/WMuCK8A9rf8JmvzPyErn6QTx0P83YoyH4j82tdr7gs0OGF/F9D9dY5/43jrf1WgQCBj3hixjImVTZF+1w==,iv:jKlsTdRCbvtvtyewztKfVLaklkdRdMLhTa5JRGcDgEU=,tag:eH7febCtsxkY5KKu816wYg==,type:str]
    known_hosts: ENC[AES256_GCM,data:6qiRIAMCHZEH4aS8VA3Ywvj09fBUss4ghgFS/tQjkXZ2VmPtU+jx4yWw6cToil6abAN1mpWMepGLMipnJEV1v7PIaOgj6oxBOcpOndGED44ZGLGFalWniSASoxX4mWz2pzr3ctLJVH3Q9YCIHVNJtdDEe0ykn74wW4f1L4en9q+uI94sqtKLKe0cs4DT07DSKVPH/0vqrJR0QjUT6K1whFCl1/IinEZ5MCiq,iv:kUBbPU6SHnT1wUo55drJGHGFp2pZfN6b4aQTFwJDWJU=,tag:5KSXR6uNRmzq0LDCctUWJA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ueasdgtcm4dwg8v6pa2yt9hdu5ul0cc8x6xp5hxaay9rgah4a4qqgxxu6z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUmZiSU1ZTzBwa09IclFQ
            US90YnB2WkpJeDUyTlc1UFdHdDVEMmdXSEV3CnYwSUVmOWY4N09KMlBqWEdrVnV2
            NFhBQWN6Q1hUeWltdGE1WTl5WlpXUnMKLS0tIExtaG9aWFdES2tETk9DazlJcjRp
            V1lVdWlPVnBYYm5OUjlldkxKOXlsWjQKNOhN3ODs5ueKc8SB68zpyAdPgDv1pFKB
            k+OB5t8WL4q7rogU0NFX/Nw/1SCdS470fm3f+oat6ODs2XaoklRtUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-31T19:53:17Z"
    mac: ENC[AES256_GCM,data:rKHWIwFS49ljyKGVmGimqnbDI48HXLDnwZjDNaRPIHlYkgVcY+6LFHIo4f72tMN/euzg5Z5yC86By59XHuUxrtHlFckunk8Bb4unZPeFByZ2RNTMp9x1rsGcCvcZSWxaLMzGQXMHpQ/aQz4ZGUEG2d3wDDSv/7dYxYUP2A2xeTk=,iv:tfs3qodHzDdPXE4rXlmyNEewu40sxjYG7UtTS0w2EaU=,tag:yuaX6M01eqZmgpTbjQ8Msw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
