apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:M/aSVH3owFAJNu3Gctu2bZ2xFRdHPsy03PoCgixFHIshCKDVGTCqZG8Q9AUygMiDDngJ29/GVDveiKWiHvWEkOcSc/k9R+WAxkYwXLDBSr/fZqku7JEkqpD3ceAMa/91nX5Mp+Vegv6o5IDAqBxjC2uC5sKm2XiSsj2GQT+JVSWjyv2HQJaXFFgpQqqRWiKSUpQpxzcf61wZyDhsDi5FNaIo8ftv+YO7xLCxnnH5Z2V2B3EbMVVCTI3SY7sjFRtlkD7ap+9wMnGIBqh/Cfbn5VtRXYZcyE8Fr0IwG2Ux5NrS2O6B8/hCfMAT7knOjyi7LIbJixvpxXOTTyV7WLf6UfptCbwZuA2oy379bL4tfWjLlWyx8xPMwH5VLG6mGLk4,iv:5e32RTLjILSBsKcwOTvCQ2M4Dg5ZZieRYrrptWahET0=,tag:g7sLeJeJtczJ2RDCrM8qzw==,type:str]
    identity.pub: ENC[AES256_GCM,data:Yph2pI0ACkXpCCRAaLNwRCLu86cvRIcwyq07o2dasKuOVeQWJUSKSbvPrJt4tacWOdAYJIgjz/0LpOAplIYLD4HeVA8yD1Diq7/lFSgJJyWMYGxZquQSfLVs5JmGvrJBwWPmdKhw13lWM+nwCTVzgERVyCneKyvF8OBuHt0bnO8M44hYx6lIKj1W2287xhIc/FZ50QH8ToEFfwlmIpnwnTMr8nW3fE+wk1XTnIrWjjdu+AYIVebhkEoecyeX02dX7kKbKpBG3yWJfWfDWg==,iv:cSQYVC6GWVhU+BLliVQ8Kk4iGF4MRFRdn7OavUNWZJs=,tag:J+79uG/eldu4kiCBC9siXw==,type:str]
    known_hosts: ENC[AES256_GCM,data:NYF7XXZqZDo58/05I8NDNJXObBgx2IwW4ugSnN6tIbzjx4R1h30K1WiAPdHr0CQHXjiqvw98jjcAbZIct2aveOqSn0pnSHS2NOvUCTi1oJqOh4CoJ3Hw7nuMKcbSdBfslIH+NsVIellemA/6gXj4COIrxJXY0D1javszmMUd6i0HS/JbLrnIwCjz8rbwjERS9pcMgc4dEJE4v8BL3MlSM5q60u4MugsAlO+x,iv:mXZtLvgS1bObdJrCEW6kzKCykjBegXWT7V0M4eDF0eU=,tag:pY4vPejYNZMFR12ZSikWFA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ueasdgtcm4dwg8v6pa2yt9hdu5ul0cc8x6xp5hxaay9rgah4a4qqgxxu6z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjYlIrZCt3eXFyMFFIcHlB
            TUdtNTcyT20vbEdJZ2syQzRzRzJRazJvUmpNCk0xVks1OTNrYjZ4NjRMZGVsS1Nr
            enVERHc1ZXc5L0Q3ejE0MXNMU1RNVlUKLS0tIENpR1VJajZ4TCtKczluVTVJUlVS
            RHRMSkpjZ2dhdHpXL2VQUnNHUmJBakUKHXBtE77b3y4H+LgBPpt6WoO8x+ZhFKZ+
            mtz/RsrtvcF8xmVoNTNcoVB2r4KiyvSFmuNLGtFXJE8PvqIpEB5I3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-21T16:43:27Z"
    mac: ENC[AES256_GCM,data:teccbT8142OAdGwIEDs5A7D8lTI9Ajy3aK2vQ6xgDBUoq3mQW8QX+iFJB6beKsx6yxhBnkrm2ZQoavoQ/KrI90pF5RS2qnFVPokalaQ5thaIP6GpzmcoVAt+6Uw/0s/aREDrjmnOoH+5okpGO65NRs6fbJhkTYCPQHUECpUwZHM=,iv:jNsaycK6x9qwzXty58XtoSWTfMBTGZOEqhColiN0NSI=,tag:yLlSHG+/eds5KS8nZwlfbQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
