apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hass
  namespace: hass
spec:
  interval: 15m
  chart:
    spec:
      chart: home-assistant
      version: 27.2.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ## Enable host networking for direct network access. True breaks K8s security.
    # hostNetwork: true
    TZ: America/Chicago   
    global:
      stopAll: false 
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}-hass"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"
    ingress:
      main:
        enabled: true
        hosts:
          - host: ha.${DOMAIN_1}
        integrations:
          traefik:
            enabled: true
            ## To do
            # middlewares:
            #   - name: local
            #     namespace: traefik
          certManager:
            enabled: true
            certificateIssuer: cloudflare  
    homeassistant:
      trusted_proxies:
      - 172.16.0.0/16
      - 172.17.0.0/16
    persistence:
      config:
        volsync:
          - name: b2
            type: restic
            credentials: s3
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: "15 17 * * *"
        readOnly: false
        accessModes:
          - ReadWriteMany        
      zigbeedongle:
        enabled: true
        type: device
        hostPath: /dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_0001-if00-port0              
    cnpg:
      main:
        mode: recovery   # Set to 'recovery' when recovery from S3, also change the revisions 
        backups:
          enabled: false  # Set to 'false' when performing new install (recovery)
          credentials: s3
          scheduledBackups:
            - name: daily-backup
              schedule: "0 15 17 * * *"
              backupOwnerReference: self
              immediate: true
              suspend: false          
          retentionPolicy: "14d"
          revison: "2"
        recovery:
          credentials: s3
          method: object_store
          # revision: "1"
    workload:
      main:
        # type: Deployment
        # strategy: RollingUpdate
        # replicas: 2      
        podSpec:
          nodeSelector:
            feature.node.kubernetes.io/usb-ff_10c4_ea60.present: "true"
            
         
