apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 15m
  chart:
    spec:
      chart: nextcloud
      version: 32.9.8
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    TZ: America/Chicago
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}-nextcloud"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"
    ingress:
      main:
        enabled: true
        hosts:
          - host: mycloud.${DOMAIN_1}
            paths:
            - path: /
              pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: cloudflare
            enabled: true
          traefik:
            enabled: true
            entrypoints:
              - websecure
    cnpg:
      main:
        # mode: recovery
        backups:
          enabled: true
          credentials: s3
          scheduledBackups:
            - name: daily-backup
              schedule: "0 30 23 * * *"
              backupOwnerReference: self
              immediate: true
              suspend: false
        recovery:
          method: object_store
          credentials: s3
    persistence:
      config:
        volsync:
        - name: config
          type: restic
          cleanupTempPVC: true
          cleanupCachePVC: true
          credentials: s3
          dest:
            enabled: true
          src:
            enabled: true
            trigger:
              schedule: 30 23 * * *
      html:
        volsync:
        - name: html
          type: restic
          cleanupTempPVC: true
          cleanupCachePVC: true
          credentials: s3
          dest:
            enabled: true
          src:
            enabled: true
            trigger:
              schedule: 30 23 * * *
      data:
        type: nfs
        path: /mnt/data1/nc_userdata
        server: ${TRUENAS_IP}
    nextcloud:
      credentials:
        initialAdminUser: ${NEXTCLOUD_USER}
        initialAdminPassword: ${NEXTCLOUD_PWD}
      general:
        default_phone_region: US
        accessIP: "${TRAEFIK_IP}"
      files:
        shared_folder_name: Shared
        max_chunk_size: 10485760
      previews:
        # https://github.com/nextcloud/server/blob/master/config/config.sample.php#L1269
        # Only the last part of the provider is needed
        providers:
          - BMP
          - GIF
          - JPEG
          - MarkDown
          - MP3
          - OpenDocument
          - PNG
          - TXT
          - XBitmap
          - PDF
      clamav:
        enabled: true