apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 15m
  chart:
    spec:
      chart: nextcloud
      version: 32.9.8
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    TZ: America/Chicago
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}-nextcloud"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"
    ingress:
      main:
        enabled: true
        hosts:
          - host: mycloud.${DOMAIN_1}
            paths:
            - path: /
              pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: cloudflare
            enabled: true
          traefik:
            enabled: true
            entrypoints:
              - websecure
    cnpg:
      main:
        # cluster:
        #   singleNode: true
        pgVersion: 15
        # mode: recovery
        backups:
          enabled: true
          credentials: s3
          scheduledBackups:
            - name: daily-backup
              schedule: "0 15 22 * * *"
              backupOwnerReference: self
              immediate: true
              suspend: false
        recovery:
          method: object_store
          credentials: s3
    persistence:
      config:
        volsync:
        - name: config
          type: restic
          cleanupTempPVC: true
          cleanupCachePVC: true
          credentials: s3
          dest:
            enabled: true
          src:
            enabled: true
            trigger:
              schedule: 15 22 * * *
      data:
        enabled: true
        type: nfs
        path: /mnt/data1/nc_userdata
        server: ${TRUENAS_IP}
      html:
        volsync:
        - name: html
          type: restic
          cleanupTempPVC: true
          cleanupCachePVC: true
          credentials: s3
          dest:
            enabled: true
          src:
            enabled: true
            trigger:
              schedule: 15 22 * * *
    nextcloud:
      collabora:
        enabled: true
        password: "${NEXTCLOUD_PWD}"
      credentials:
        initialAdminPassword: "${NEXTCLOUD_PWD}"
        initialAdminUser: "${NEXTCLOUD_USER}"
      general:
        accessIP: ${TRAEFIK_IP}
        default_phone_region: US
      previews:
        providers:
        - BMP
        - GIF
        - JPEG
        - Krita
        - MarkDown
        - MP3
        - OpenDocument
        - PNG
        - TXT
        - XBitmap
