apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: nextcloud
    namespace: nextcloud
spec:
    interval: 15m
    chart:
        spec:
            chart: nextcloud
            version: 32.8.6
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 15m
    timeout: 20m
    maxHistory: 3
    driftDetection:
        mode: warn
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:
        global:
            stopAll: false
        TZ: America/Chicago
        credentials:
          s3:
            type: s3
            url: "${S3URL}"
            bucket: "${S3PREFIX}-nextcloud"
            accessKey: "${S3ID}"
            secretKey: "${S3KEY}"
            encrKey: "${S3KEY}"
        ingress:
            main:
                enabled: true
                hosts:
                    - host: thecloud.${DOMAIN_1}
                      paths:
                        - path: /
                          pathType: Prefix
                integrations:
                    certManager:
                        certificateIssuer: cloudflare
                        enabled: true
                    # homepage:
                    #     description: ""
                    #     enabled: true
                    #     group: Apps
                    #     icon: ""
                    #     name: ""
                    #     widget:
                    #         custom:
                    #             key: ""
                    #         enabled: false
                    traefik:
                        enabled: true
                        entrypoints:
                            - websecure
        nextcloud:
            credentials:
                initialAdminPassword: ${ADMIN_PASSWORD}
                initialAdminUser: admin
            notify_push:
                enabled: true
        persistence:
            data:
                enabled: true
                path: /mnt/data1/nc_userdata
                readOnly: false
                server: ${TRUENAS_IP}
                type: nfs
