apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app-template
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template #dummy chart
      version: 14.5.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: default
  values: