apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-application
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: my-application
      version: '1.0.0'
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: default
  values: