apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  releaseName: longhorn
  chart:
    spec:
      chart: longhorn
      version: 1.8.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    defaultSettings:
      # Increase to 3 for a multi-node cluster
      defaultReplicaCount: 3
      # Overprovisioning might be needed when using volsync
      storageOverProvisioningPercentage: 100000
      # v2DataEngine: true
    persistence:
      # Set to false to pick another CSI as default
      defaultClass: true
      # Increase to 3 for a multi-node cluster
      defaultClassReplicaCount: 3
      # Additional settings for RWX support
      storageClass:
        parameters:
          # This parameter specifies that the storage class supports RWX volumes
          shareManagerNodeSelector: ""
          # Optional: If you want to control where the share manager pods are scheduled
          # shareManagerTolerations: "key=value:NoSchedule"
          # Allowed topologies for controlling where the volumes can be scheduled
          allowedTopologies:
          - matchLabelExpressions:
            - key: topology.kubernetes.io/region
              values:
              - us-west-1  # Example, adjust based on your cluster's topology
        # Ensure that the access mode includes RWX
        accessModes:
          - ReadWriteMany
        # It's recommended to use 'WaitForFirstConsumer' for better volume binding control
        volumeBindingMode: WaitForFirstConsumer