---
# yaml-language-server: schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  interval: 15m
  chart:
    spec:
      chart: vaultwarden
      version: 28.8.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    global:
      stopAll: false

    TZ: America/Chicago
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}-vaultwarden"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"       
    ingress:
      main:
        enabled: true
        hosts:
          - host: vault.${DOMAIN_1}
        integrations:
          traefik:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: cloudflare 
    vaultwarden:
        allowSignups: true
        verifySignup: false
        requireEmail: false
        allowInvitation: true
        showPasswordHint: false
        enableWebVault: true
        admin:
          enabled: true
          disableAdminToken: false
          token: ${VW_TOKEN}
    persistence:
      data:
        size: 10Gi
        # Optional: Uncomment and configure if you want VolSync backups later
        volsync:
          - name: data
            type: restic
            credentials: s3
            src:
              enabled: true
              schedule: "45 14 * * *"  # 9:45 am dst on
            dest:
              enabled: true  # Disable restore for clean install
    cnpg:
      main:
        mode: recovery  # Set to 'recovery' when recovery from S3, also change the revisions 
        backups:
          enabled: false  # Set to 'false' when performing new install (recovery)
          credentials: s3
          scheduledBackups:
            - name: daily-backup
              schedule: "0 45 14 * * *"
              backupOwnerReference: self
              immediate: true
              suspend: false           
          retentionPolicy: "7d"
          revision: "2"
        recovery:
          method: object_store
          credentials: s3
          revision: "1"
    workload:
      main:
        # type: Deployment
        # strategy: RollingUpdate
        # replicas: 2      
        podSpec:
          containers:
            main:
              env:
                DOMAIN: "https://{{ if .Values.ingress }}{{ if .Values.ingress.main.enabled }}{{ ( index .Values.ingress.main.hosts 0 ).host }}{{ else }}placeholder.com{{ end }}{{ else }}placeholder.com{{ end }}"
                DATABASE_URL:
                  secretKeyRef:
                    name: cnpg-main-urls
                    key: std
              envFrom:
                - configMapRef:
                    name: vaultwardenconfig
                - secretRef:
                    name: vaultwardensecret          
