---
# yaml-language-server: schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  interval: 15m
  chart:
    spec:
      chart: vaultwarden
      version: 28.6.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    global:
      stopAll: false

    TZ: America/Chicago
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}-vault"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"       
    ingress:
      main:
        enabled: true
        hosts:
          - host: vault.${DOMAIN_1}
        integrations:
          traefik:
            enabled: true
            # middlewares:
            #   - name: local
            #     namespace: traefik
          certManager:
            enabled: true
            certificateIssuer: cloudflare 
    vaultwarden:
        allowSignups: true
        verifySignup: false
        requireEmail: false
        allowInvitation: true
        showPasswordHint: false
        enableWebVault: true
        admin:
          enabled: true
          disableAdminToken: false
          token: ${VW_TOKEN}
    persistence:
      data:
        volsync:
          - name: b2
            type: restic
            credentials: s3
            dest:
              enabled: true                          
            src:
              enabled: true
              trigger:
                schedule: 0 20 * * *
    cnpg:
      main:
        mode: recovery  # Set to 'recovery' when recovery from S3, also change the revisions 
        backups:
          enabled: false  # Set to 'false' when performing new install (recovery)
          credentials: s3
          scheduledBackups:
            - name: daily-backup
              schedule: "0 0 21 * * *"
              backupOwnerReference: self
              immediate: true
              suspend: false           
          retentionPolicy: "7d"
        recovery:
          method: object_store
          credentials: s3
