---
# yaml-language-server: schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: xteve
  namespace: xteve
spec:
  interval: 15m
  chart:
    spec:
      chart: xteve
      version: 15.5.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    TZ: America/Chicago
    global:
      stopAll: false
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}-tv"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${XTEVE_IP}
        ports:
          main:
            port: 34400
            targetPort: 34400
    # persistence:
    #   config:
    #     # storageClass: ceph-filesystem
    #     volsync:
    #     - name: config
    #       type: restic
    #       credentials: s3
    #       dest:
    #         enabled: true
    #       src:
    #         enabled: true
    #         # trigger:
    #         #   schedule: 30 1 * * *            
    persistence:
      config:
        enabled: true
        storageClass: ceph-nvme
        size: 1Gi
        accessModes:
          - ReadWriteMany