---
# yaml-language-server: schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: xteve
  namespace: xteve
spec:
  interval: 15m
  chart:
    spec:
      chart: xteve
      version: 15.5.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    TZ: America/Chicago
    global:
      stopAll: false
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}-tv"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${XTEVE_IP}
        ports:
          main:
            port: 34400
            targetPort: 34400
    persistence:
      data:
        enabled: true
        size: 10Gi
        volsync:
          - name: tv
            type: restic
            credentials: s3
            src:
              enabled: true
              schedule: "0 17 * * *" 
            dest:
              enabled: false  # Disable restore for clean install
      config:
        enabled: true
        size: 1Gi
        volsync:
          - name: tv-config
            type: restic
            credentials: s3
            src:
              enabled: true
              schedule: "0 17 * * *"  
            dest:
              enabled: false  # Disable restore for clean install
