apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: jellyfin
    namespace: jellyfin
spec:
    interval: 5m
    chart:
        spec:
            # renovate: registryUrl=https://charts.truechartsoci.org
            chart: jellyfin
            version: 20.6.12
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    timeout: 20m
    values:
      portal:
        open:
          enabled: false
      global:
        stopAll: false
      credentials:
        s3:
          type: s3
          url: "${S3URL}"
          bucket: "${S3PREFIX}-jellyfin"
          accessKey: "${S3ID}"
          secretKey: "${S3KEY}"
          encrKey: "${S3KEY}"
      ingress:
        main:
          enabled: true
          hosts:
            - host: jelly.${DOMAIN_1}
          integrations:
            traefik:
              enabled: true
            certManager:
              enabled: true
              certificateIssuer: cloudflare  
      persistence:
        config:
          size: 1Gi
          volsync:
          - name: config
            type: restic
            # cleanupTempPVC: true
            # cleanupCachePVC: true
            credentials: s3
            dest:
              enabled: true
            src:
              enabled: true


      # persistence:
      #   config:
      #     enabled: true
      #     storageClass: ceph-filesystem
      #     size: 1Gi
      #     accessModes:
      #       - ReadWriteMany